name: Deploy SIM release-note
on:
  push:
    branches:
      - main
      - draft-dls-v3
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dls-release-notes
    steps:
      - uses: actions/checkout@v2

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree build add --all
      - run: git commit -m "Automatic Deploy action run by github-actions"
      - run: git push origin HEAD:gh-pages --force
